# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81f8de9ea7758f3783250ab3ed5d8d2873322c21c3b8fe24f84822d3366a191bd5a5d0a638ab2b8d0bce1d91539631ff3415e36815eb3af9a31aff47379d4f4

test:
  secret_key_base: e43311298ca797062335f00f348a2b03718c3fb15f0d8f7cd49b1200ec18b48a6800378ec6564c7e5b2200663a320f3620f44b0651cea0334e6a2c8932e4693b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 2337f4aa064c58153c1d73401d7cdfc6a19933915cddaa38b4eb91fe221c1282a9d4eabba828e343825bfa8d5c803fa819df6058b15459281bfd5e1dcb51a5c9
